language: node_js
notifications:
  email: false
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+(-(alpha|beta)\\.\\d+)?$/"

jobs:
  include:
  - stage: test
    before_script: npm ls --production >/dev/null
    after_success:
      - npm run coverage:report
      - npm run snapshot
  - stage: deploy
    name: Publish
    script: skip
    deploy:
      provider: script
      skip_cleanup: true
      script: npx semantic-release@beta
      on:
        all_branches: true
  - stage: deploy
    name: Deploy Documentation
    script: skip
    before_deploy:
      - npm run build-storybook
      - git config --global user.email "$GIT_EMAIL"
      - git config --global user.name "$GIT_NAME"
    deploy:
      provider: script
      skip_cleanup: true
      script: npm run deploy


env:
  global:
  - FORCE_COLOR=1
  - NPM_CONFIG_COLOR=always
  - secure: fCMfMT5TYR+h/5D0DFj1lJI6MhRZdnN8/RoBCx9oREPGd/Mh71PuLrqr9b5kksMOIuh/2JjkuSm7CsgBd7Ug2JY+yjVV9KxIBD84DePPcCr6ePtsUP5uLufZU1MP5katrCMNfYtUreQuuQb4+cr0JzY/2fsyE895Gi2rGE7K9q9f/bGPM0m1h2gwKao8fIUFRWY9J7rIGbYPHQE6quw/zQM2byJ5+SNKa6xSjV4prfuLY1SDowACcI3O/aPyTUsciZMPW5luvVXVnJNN+iKbnPKjhDAeoN8UE6f1rfz6xVhEmAk40nIrddO+aS9VmMVAV7nQpg4qcUJZZ9UKpagIK+GlOYYEjJy6+MlDwoHpGMZjCc2LBVMPv/AXUSsKpFDZwzTNo5tCZbo1ermM2pulSDb/eZEaFTrmpttPfmBajNF4i/5odKc+RCJs0+Op/zrqpdZbQl8ryB7/2m4uqebS+wJILrc7kr0H5XajttBN0eFCjtfxGxj3WyOmP7gzUYyEhoWE4B8uwB5ZeDUUOmOm3mDmYGKg0nB0bofkTi/VNwnQza+lBy/GsN3AgIxK/tkHnvSFqd22aQki0SZKAAqDEQf+B3Mo27vMqnuBc/hz8hAwRPYBWzyjifT9G+jpkCM27lHtolD43e2+uHRjdHu69XWFXl1x0wgR/89bH0rtUU0=
  - secure: gE2Qq4hFxVYzB5hYJhf1wm1yNUFC86EbTqZztob6AG8Zs21yq7HYKibS9BwwiXVfceYHGGr95XxrjjNbVhGyj+2CMEFXS76lF6jfkIlc+cTY1pLA+vBvyeuHirYcKiN2FfpUCM40goM8CgFU+FdObch255dbhGdwBSSswEn7wn+vmsXLZtG1OtIh7MbIJVKoVu7W7JeprcbxiG7sgfuleqWcFz/FCSo+Pvj++j9YfLvgFhlZMcSus1kXa0r3wmEVM096Xm5JA8vdvnL/nAlbuJ2SMyfbrCG203pm1YRCILBM7KucrjwGw6V7Z7zFn4Ic6mE3bAKT3/UIdX1KppgFGxC/pY48qoqwqlm9lb6HVOSGYKJs6bY0P6CBy9+5ktaXIdCQjgTxpdEp7CsJmVXxZ59RzdkbWThpmAwsLO0gonpRbBOWjld2Pt4Mz7sUQTd0VDVi2xFztxUbfu291zVbYTtvAz77rY2RZBMypl9pxEE32rU4jL5Trq/ofNZPTlodzZdkl+f3OiKLJz3Pw6nVOsRkhVnrMQHOYsNiDvv8rscDFBxgDUH1tsDq/W4raG4OgY0+nN3CcPUirqNZq3qNuty/6aRLh/W815cUWOQ3vGyeA3GtX2GWQP+7q35fHtgIA/7/g7JzKipS4W71G1s/VlOOmbT51KJ84D0rt595M6I=
