version: "~> 1.0"
cache:
  npm: true
notifications:
  email: false
import:
- source: form8ion/.travis-ci:node.yml
- source: form8ion/.travis-ci:cypress.yml
- source: form8ion/.travis-ci:chromatic.yml
- source: travi-org/.travis-ci:authenticated-semantic-release-stage.yml
- source: travi-org/.travis-ci:authenticated-netlify-deploy-stage.yml

jobs:
  include:
  - stage: test
    after_success:
    - npm run coverage:report
    - npm run snapshot
stages:
  - test
  - deploy

env:
  global:
  - secure: gE2Qq4hFxVYzB5hYJhf1wm1yNUFC86EbTqZztob6AG8Zs21yq7HYKibS9BwwiXVfceYHGGr95XxrjjNbVhGyj+2CMEFXS76lF6jfkIlc+cTY1pLA+vBvyeuHirYcKiN2FfpUCM40goM8CgFU+FdObch255dbhGdwBSSswEn7wn+vmsXLZtG1OtIh7MbIJVKoVu7W7JeprcbxiG7sgfuleqWcFz/FCSo+Pvj++j9YfLvgFhlZMcSus1kXa0r3wmEVM096Xm5JA8vdvnL/nAlbuJ2SMyfbrCG203pm1YRCILBM7KucrjwGw6V7Z7zFn4Ic6mE3bAKT3/UIdX1KppgFGxC/pY48qoqwqlm9lb6HVOSGYKJs6bY0P6CBy9+5ktaXIdCQjgTxpdEp7CsJmVXxZ59RzdkbWThpmAwsLO0gonpRbBOWjld2Pt4Mz7sUQTd0VDVi2xFztxUbfu291zVbYTtvAz77rY2RZBMypl9pxEE32rU4jL5Trq/ofNZPTlodzZdkl+f3OiKLJz3Pw6nVOsRkhVnrMQHOYsNiDvv8rscDFBxgDUH1tsDq/W4raG4OgY0+nN3CcPUirqNZq3qNuty/6aRLh/W815cUWOQ3vGyeA3GtX2GWQP+7q35fHtgIA/7/g7JzKipS4W71G1s/VlOOmbT51KJ84D0rt595M6I=
  - secure: Snk4zI4gg9+lu0w0KnW1pEqk6b2Ff9W1bwIF6wfrmOybn8qTcTI8+pbPa8eEifJJGm4YKGuTUtdRJlBpruRc6lbOSQhMMpIwIJvOJ4HDhcqcEjOekMEzG0j8f+E7qjyWuywLnmIEkoR1upcppnvedQ0BVQVWbQpxB1qHBN7Wma6/usXJ/njPUjgf1DYXehiLfZ7MiVNmIA9kpYkxAXNpfxKCDZzarLCGaPyejZgObCiyH4y1Ra6UwX3ob5C30vzbXDB4A+vl9jEk8TPdW5f7xhp2dgimGhRtOgPAOikZL7ZElkZCvmG2hZvzpSuqPV+FMBNJDTg9NcyCfwtFjEe+rOGjbcdz2D3FJ65FsuE3LNa/gKiDbt982gqhkMrgGDYBGDqOm89HJk02xOSRxm2hjVToH/BSRknHtEzIgX8oAf0vYzX+t4yfWl5VUHIMhqri2cC7nrEcHAR1g7wyh5OcCshkjaAUQ3LkjIFSbC8hvcOFU3eUpSd6eCstkJAI2QwHxCokiXp97iApUvsuUbXYIjPLBv/wAkhd/yCoPUlFmVVi7ymYtMssyosYmTGOMKowpBXERgOVthR/gIsIi1EH1FvJtlaxeDUxaCpf9iVsD0ZO4BfsGLI0PaWxyo/JW7s3I2BvpqE9qxjQBiOxjoeybLm5AEWNmI6RGuR4eF2N2H0=
  - secure: mEnjWzIDySrT6FQofaCfkkwYnsevj+n31tE/tj3h4BWWDpUQY/W+mfjq2YxgHSK44cAErw3uVz0ehmob2mZgzaRWpxJ0PF861jxZHYTo9d4am9jL+XPB+BxW84UAcyNUS8EqVIVP7htl6xrnVbPmQZSx/oPG0/YLxI7sF2IRSeN7HJduCpMgvipedMywXMYrVzSpgcpaaS8HpIVgBYLcj1qDNJ1dosV9LpPFIHkBnvwuYYerUwAAHe+D4hb1GLYUbJwkiCry+ZQ6u7PGrdWcQdIN4Sb5T8htp9bjsCZTfzI1pWcY2FyEtBdr5BAqRUmn9zD4WqVNC1Wa0/Z0MDBLEiYFV9NC5jqOh8uFefeHo42iMvpfTvmyrcih6qFC6CUlhUgh11wdK8CuD/bXUBYZFp6/w//uau+fMikYnJ16kssRSMBfXZrUg0DGR6dyqPk9XA+LMMUTMJg2iGuBXeam3s0yx+4I0JRntaH+JzN8ISxZv79yawAnfomOn5KqXspZXU4Wd9+NXeoLg/vsvQlnENOdfqnCItfwGvgpy4hrmtCXWb/r3d7NrSqKnd7nDIHtgS61vxDaCme9T4TgXW6rXc8xdq+XCub8gtkrDboCQR+YxWdhCAS2cAmSZVVWB66NcbyP8gPL9fGuD+27NF2R1VpJYfxUdH2zI5nawfItIKc=
  - secure: gI1+KqchpPacoKGp1KzCmP+J8YkNke8iywbirUr8prrmDF5k02v2EqQ7Zr0GLJFPBzW2J0lvIBevPm3/FnP8vHj3chl9RU3EMNoVB61hARhyZtoqs+J8ijNo1himBgo5OF/g3DX2HQG7bL9y2L8fVw8CbVUSEF1ZatZFzZ1D4J8ikjyLbgeSaRt2c7/A5Oixxr6qKMIR88l+HmOIKyb4nFZ/MMN+rrVbgmHRWwz5wxwoYbk4cekCFeZYXrVzyefrrSc7ebmECkw/JEZ7j1gnrJGLG/H0mDQxM6PZ/lOcBfXExHFk+rLLEe3Jt584rJoGQRRHExvGYAI5wCft39skm/8NxuDvQESkzUNSlsL3S/aFxqMOLrweajeXc6cell5jKNY3/ngTwG6Rf8ui67xrqUhy/gBPLkeE2w+N2I7t9ed2Gtfnx2Qv0aoFagf2UMAI8J9IWtYbQbqNzv81S4gbsUkqbfOoD5pg6kR1jCYZlcUhcSZY9glvcTHDVWZUvnV3qWzvNfjEUY+4lQAo0KQHHdHb5VgVJmjY+uGdoh9Pd4wHq7o9w6T/GRt3fePdOD9USlRwbG36RcBGVq6XmJByiZy/IderjG0l6aXjCEN8auc+5Szof9uoZBM0X3rAEcDALPpEGS7Q6p2ZlwT8Sa4mZsSI4fIaFaYFPzwhhBpVU3M=
