name: 'Chromatic'
on: push

jobs:
  upload-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          fetch-depth: 0
      - uses: bahmutov/npm-install@v1
      - uses: chromaui/action@c93e0bc3a63aa176e14a75b61a31847cbfdd341c # v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: build:storybook
          autoAcceptChanges: master
          exitOnceUploaded: true
